---
flowehr_id: flowehr
location: uksouth
environment: infra-test
accesses_real_data: false
core_address_space: 10.0.0.0/24

transform:
  spark_version: 3.3.1
  repositories:
    - url: https://github.com/UCLH-Foundry/FlowEHR-Data-Pot

serve:
  github_owner: UCLH-Foundry
